miniproject/collegespace/urls.py
from . import views
from django.conf.urls import url

app_name = 'collegespace'

urlpatterns = [
    # /register/   :   url for registering
    url(r'^register/$', views.register, name='register'),

    # /home/   :   home page
    url(r'^home/$', views.home, name='home'),

    # /login_user/   :   to login
    url(r'^login_user/$', views.login_user, name='login_user'),

    # /logout_user/   :   to logout
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    # /search/   :   to search a user
    url(r'^search/$', views.search, name='search'),

    # /profile/###   :   to view a profile
    url(r'^profile/(?P<prof_id>[0-9]+)/$', views.profile, name='profile'),

    # /add_friend/###   :   to add friend
    url(r'^add_friend/(?P<prof_id>[0-9]+)/$', views.add_friend, name='add_friend'),

    # /post_text/   :   to post text
    url(r'^post_text/$', views.post_text, name='post_text'),

    # /post_img/   :   to post text
    url(r'^post_img/$', views.post_img, name='post_img'),

    # /delete_post/###   :   to delete post
    url(r'^delete_post/(?P<post_id>[0-9]+)/$', views.delete_post, name='delete_post'),

    # /like_post/###   :   to like post
    url(r'^like_post/(?P<post_id>[0-9]+)/$', views.like_post, name='like_post'),

    # /delete_comment/###   :   to delete comment
    url(r'^delete_comment/(?P<comment_id>[0-9]+)/$', views.delete_comment, name='delete_comment'),

    # /like_comment/###   :   to like comment
    url(r'^like_comment/(?P<comment_id>[0-9]+)/$', views.like_comment, name='like_comment'),

    # /comment/   :   to comment
    url(r'^comment/', views.comment, name='comment'),
]

miniproject/miniproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('collegespace.urls')),
]

miniproject/collegespace/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

'''
class Profile(models.Model):
    GENDERS = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    posts = models.CharField(max_length=5000)
    pics = models.ImageField()
    friends = ArrayField(
        models.IntegerField(), null=True, blank=True
    )
    dob = models.DateField(default=datetime.today)
    gender = models.CharField(max_length=1, choices=GENDERS, default='M')

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

'''


class Profile(models.Model):
    GENDERS = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    # posts = models.CharField(max_length=5000)
    # pics = models.ImageField()
    # friends = ArrayField(models.IntegerField(), null=True, blank=True)
    dob = models.DateField(default=datetime.today)
    gender = models.CharField(max_length=1, choices=GENDERS, default='M')

    def __str__(self):
        return self.user.username


class Posts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)


class TextPost(Posts):
    text = models.CharField(max_length=1000)


class ImagePost(Posts):
    description = models.CharField(max_length=1000)
    pic = models.ImageField()


class Friends(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    friend = models.IntegerField()


class Comments(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=1000)
    likes = models.IntegerField(default=0)

miniproject/collegespace/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['dob', 'gender']

miniproject/collegespace/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm, ProfileForm
from django.contrib.auth.models import User
import datetime
from .models import Friends, ImagePost, Posts, TextPost, Comments
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist


# Registering
# messaging

@login_required
def home(request):
    if not request.user.is_authenticated:
        return render(request, 'collegespace/login.html')
    else:
        message = request.user.username
        posts = get_posts()
        return render(request, 'collegespace/home.html', {
            'message': message,
            'posts': posts,
        })


@login_required
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'collegespace/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                message = username
                return render(request, 'collegespace/home.html', {
                    'message': message,
                    'posts': get_posts(),
                })
            else:
                return render(request, 'collegespace/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'collegespace/login.html', {'error_message': 'Invalid login'})
    return render(request, 'collegespace/login.html')


@login_required
def search(request):
    searched_str = request.GET.get("searched_str")
    print(searched_str)
    if searched_str:
        results = User.objects.filter(username__icontains=searched_str)
    else:
        results = User.objects.all()
    return render(request, "collegespace/result.html", {
        'results': results
    })


@login_required
def profile(request, prof_id):
    user = get_object_or_404(User, pk=prof_id)
    return render(request, 'collegespace/profile.html', {
        'user': user,
    })


# to be completed
def register(request):
    if request.method == 'POST':
        u_form = UserForm(request.POST, instance=request.user)
        p_form = ProfileForm(request.POST, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()

            username = u_form.cleaned_data['username']
            password = p_form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    message = request.user.username
                    return render(request, 'collegespace/home.html', {
                        'message': message,
                        'posts': get_posts(),
                    })
        return render(request, 'collegespace/login.html')
    else:
        u_form = UserForm(instance=request.user)
        # p_form = ProfileForm(instance=request.user.profile)
        return render(request, 'collegespace/login.html', {
            'u_form': u_form,
        })


@login_required
def add_friend(request, prof_id):
    user_friends = Friends.objects.filter(user=request.user, friend=prof_id)
    if len(user_friends) == 0:
        friend = Friends(user=request.user, friend=prof_id)
        friend.save()
    frnd_list_ = Friends.objects.filter(user=request.user)
    frnd_list = []
    for frnd in frnd_list_:
        friend = User.objects.get(pk=frnd.friend)
        frnd_list.append(friend)
    return render(request, 'collegespace/added.html', {
        'frnd_list': frnd_list,
    })


@login_required
def post_text(request):
    if request.method == "POST":
        text_post = TextPost()
        text_post.text = request.POST['post']
        text_post.user = request.user
        text_post.date_created = datetime.datetime.now()
        text_post.save()
        return render(request, 'collegespace/home.html')
    else:
        return render(request, 'collegespace/home.html')


@login_required
def post_img(request):
    if request.method == 'POST':
        img_post = ImagePost()
        img_post.pic = request.FILES['profilepic']
        img_post.description = request.POST['description']
        img_post.user = request.user
        img_post.date_created = datetime.datetime.now()
        img_post.save()

    return render(request, 'collegespace/uploadphoto.html')


def get_posts():
    posts_to_return = []
    posts = Posts.objects.order_by('-date_created')
    for post in posts:
        a = TextPost.objects.filter(posts_ptr_id=post.id)
        if len(a) == 0:
            a = ImagePost.objects.filter(posts_ptr_id=post.id)
        for b in a:
            posts_to_return.append(b)
    return posts_to_return


@login_required
def delete_post(request, post_id):
    try:
        post = Posts.objects.get(pk=post_id)
        post.delete()
        return render(request, 'collegespace/home.html')
    except ObjectDoesNotExist:
        return render(request, 'collegespace/home.html')


@login_required
def like_post(request, post_id):
    try:
        post = Posts.objects.get(pk=post_id)
        post.likes += 1
        post.save()
        return render(request, 'collegespace/home.html')
    except ObjectDoesNotExist:
        return render(request, 'collegespace/home.html')


@login_required
def delete_comment(request, comment_id):
    try:
        cmnt = Comments.objects.get(pk=comment_id)
        cmnt.delete()
        return render(request, 'collegespace/home.html')
    except ObjectDoesNotExist:
        return render(request, 'collegespace/home.html')


@login_required
def like_comment(request, comment_id):
    try:
        cmnt = Comments.objects.get(pk=comment_id)
        cmnt.likes += 1
        cmnt.save()
        return render(request, 'collegespace/home.html')
    except ObjectDoesNotExist:
        return render(request, 'collegespace/home.html')


@login_required
def comment(request):
    if request.method == "POST":
        cmnt = request.POST['comment']
        post = Posts.objects.get(pk=int(request.POST['post']))
        print("----------" + str(post.likes))
        c = Comments()
        c.comment_text = str(cmnt)
        c.post = post
        c.save()
    return render(request, 'collegespace/home.html')

miniproject/collegespace/templates/collegespace/added.html
<!-- shows the friends of a person -->

{% extends 'collegespace/template.html' %}

{% block body %}<br>
added<br><br>
{% for frnd in frnd_list %}
<!-- Edit this some -->
{{ frnd.username }}

{% endfor %}

{% endblock %}

miniproject/collegespace/templates/collegespace/home.html
{% extends 'collegespace/template.html' %}

{% block body %}
<div class="posts">
    <div class="postForm">
            <form action="{% url 'collegespace:post_text' %}" method="post">
            {% csrf_token %}
            <textarea id="post" rows="5" cols="70" name="post"></textarea>
            <input type="submit" name="send" value="Post" style="background-color: #DCE5EE; border: 1px solid #666;size: 20px;">
        </form>
    </div>

    <div class="profilePosts">

        {% for post in posts %}
            {{ post.text }}<br>
            {{ post.description }}<br>
            Likes:{{ post.likes }}<br>

            <a href="{% url 'collegespace:like_post' post.id %}">Like</a>
            <a href="{% url 'collegespace:delete_post' post.id %}">Delete</a>
            <br>

            {% for comment in post.comments_set.all %}
                ----- Comment ------
                <br>
                {{ comment.comment_text }}<br>
                Likes:{{ comment.likes }}<br>
                <a href="{% url 'collegespace:like_comment' comment.id %}">Like</a>
                <a href="{% url 'collegespace:delete_comment' comment.id %}">Delete</a>
                <br>
            {% endfor %}
            <form action="{% url 'collegespace:comment' %}" method="post">
                {% csrf_token %}
                Comment : <textarea rows="5" cols="60" name="comment"></textarea>
                <input type="hidden" name="post" value="{{ post.id }}">
                <input type="submit" name="send" value="Post" style="background-color: #DCE5EE; border: 1px solid #666;size: 20px;">
            </form>
            <br><br><br>
        {% endfor %}

    </div>


    <img src="" height="250" width="200" alt="" title="profile img">
    <br />
    <div class="textheader">{{ user.get_username }} profile</div>
    <div class="profileleftsidecontent"><strong>content about the profile</strong><br />
    <p>Here is the Introduction</p>
    </div>
    <div class="textheader">{{ user.get_username }}'s Friends</div>
    <div class="profileleftsidecontent">
        <img src="" height="50" width="40">
        <img src="" height="50" width="40">
        <img src="" height="50" width="40">
        <img src="" height="50" width="40">
        <img src="" height="50" width="40">
        <img src="" height="50" width="40">
    </div>
</div>

{% endblock %}

miniproject/collegespace/templates/collegespace/login.html
{% extends 'collegespace/template.html' %}

{% block body %}
<div class ="login1" style="float:left;">
            <h2>Already a Member? Login below ...</h2>
            <form role="form" action="{% url 'collegespace:login_user' %}"  method="post">
                {% csrf_token %}
    
    Username : <input id="id_username" name="username" type="text">
    <br>
    Password : <input id="id_password" name="password" type="password">
    <br>
   <input type="submit" name="reg" value=" Login In">
</form>
            </div>
           <div class="login2" style="float: right; width: 240px;">
            <h2>Sign up Below ...</h2>
           <form action="{% url 'collegespace:register' %}" method="post">
               {% csrf_token %}
           <!--<input type="text" size="40" name="first_name"  class="auto-clear" title="First Name" placeholder="first name"><p />
           <input type="text" size="40" name="last_name" class="auto-clear" title="Last Name" placeholder="last name"><p />
           <input type="text" size="40" name="username" class="auto-clear" title="Username" placeholder="user name"><p />
           <input type="text" size="40" name="email" class="auto-clear" title="Email" placeholder="email address"><p />
           <input type="text" size="40" name="email2" class="auto-clear" title="Repeat Email" placeholder=" Repeat email"><p />
           <input type="password" size="40" name="password" placeholder="new password"><p />
           <input type="password" size="40" name="password2" placeholder="confirm password"><p />-->
               {{ u_form.as_p }}
           <input type="submit" name="reg" value="Sign Up!">
           </form>
           </div>

{% endblock %}

miniproject/collegespace/templates/collegespace/profile.html
{% extends 'collegespace/template.html' %}

{% block body %}

{{ user.username }} -- <a href="{% url 'collegespace:add_friend' user.id %}">Add Friend</a>

{% endblock %}

miniproject/collegespace/templates/collegespace/result.html
<!-- It shows the search results -->

{% extends 'collegespace/template.html' %}

{% block body %}
<br><br><br><br><br><br><br><br><br><br>
        {% for person in results %}
        <!-- Make a box arount the result and add space for name profile photo and addfriend button -->
        <!-- this is result -->
            <a href="{% url 'collegespace:profile' person.id %}"> {{ person.username }} -- {{ person.id }}</a><br/>
        {% endfor %}
{% endblock %}

miniproject/collegespace/templates/collegespace/template.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'collegespace/style.css' %}" />



<div class="header">
	<div id="wrapper">
		<div class="logo">
			<h2>College Space</h2>
		</div>
		<div id="menu">
			<a href="#">Home</a>
			<a href="#">About</a>
			<a href="#">Profile</a>
			<a href="{% url 'collegespace:logout_user' %}">Logout</a>
		</div>

	</div>

	<form method="GET" action="{% url 'collegespace:search' %}">
		<input type="text" size="40" name="searched_str"  class="auto-clear" title="Search" placeholder="Search">&nbsp;<input type="submit" name="reg" value="Search"><br><br>
	</form>
</div>
<br>
<br>
<a href="{% url 'collegespace:post_img' %}">Upload Photo</a>
{% block body %}
{% endblock %}

miniproject/collegespace/templates/collegespace/uploadphoto.html
{% extends 'collegespace/template.html' %}

{% block body %}
<div class="posts">
    <h2>Upload your Photos:</h2>
    <hr />
    <form action="{% url 'collegespace:post_img' %}" method="POST" enctype="multipart/form-data" name = 'pic'>
        {% csrf_token %}
        <input type="file" name="profilepic" />
        <input type="text" name="description">
        <input type="submit" name="uploadpic" value="Upload Image">
    </form>
    <br>
    <h2> Albums:</h2><hr>
    <table>
        <tr>
            <td>
                <div class='albums'>
                    <a href='view_phot0'>
                    <img src='#' height='170' width='170'><br><br>
                    album_title
                    </a>
                    <center>
                    <form method='POST' action='$user'><br>
                        {% csrf_token %}
                        <input type='submit' name='remove_album_$uid' value='Remove Album' style="float: right;">
                    </form>
                    </center>
                </div>
            </td>
        </tr>
    </table>
</div>
{% endblock %}